language: python
python:
  - "3.6"
  - "3.7"
env:
  - PYTHONPATH=$PWD/peon
install:
  - pip install -r ./peon/requirements.txt

script:
  - coverage run -m pytest ./peon/tests
  - coverage xml -o coverage-report.xml
  - mutmut --paths-to-mutate ./peon/src --tests-dir ./peon/tests run || true && mutmut results
  - bandit -r ./peon -x ./peon/tests

after_success:
  - bash <(curl -s https://codecov.io/bash)
